drop table zhengh_teachingclass18;
drop table Zhengh_Teacher18;
drop table Zhengh_Student18;
drop table  Zhengh_StudentScore18;
drop table Zhengh_Faculty18;
drop table zhengh_class_course18;
drop table Zhengh_AdClass18;
drop table Zhengh_Major18;
drop table Zhengh_Course18;
